/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.8 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(DeviceInfo, DeviceInfo, AUTO)


PB_BIND(TouchSensorReading, TouchSensorReading, AUTO)


PB_BIND(GasSensorReading, GasSensorReading, AUTO)


PB_BIND(BmeSensorReading, BmeSensorReading, AUTO)


PB_BIND(PhotoRequest, PhotoRequest, AUTO)




