/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.8 */

#ifndef PB_MESSAGES_PB_H_INCLUDED
#define PB_MESSAGES_PB_H_INCLUDED
#include <pb.h>
#include "google/protobuf/timestamp.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _TouchValue {
    TouchValue_NONE = 0,
    TouchValue_LOW = 1,
    TouchValue_HIGH = 2
} TouchValue;

/* Struct definitions */
typedef struct _DeviceInfo {
    int32_t id;
    char name[50];
} DeviceInfo;

typedef struct _TouchSensorReading {
    bool has_device_info;
    DeviceInfo device_info;
    bool has_timestamp;
    google_protobuf_Timestamp timestamp;
    TouchValue touch_value;
} TouchSensorReading;

typedef struct _GasSensorReading {
    bool has_device_info;
    DeviceInfo device_info;
    bool has_timestamp;
    google_protobuf_Timestamp timestamp;
    int32_t gas_value;
} GasSensorReading;

typedef struct _BmeSensorReading {
    bool has_device_info;
    DeviceInfo device_info;
    bool has_timestamp;
    google_protobuf_Timestamp timestamp;
    int32_t temperature_value;
    uint32_t pressure_value;
    int32_t humidity_value;
} BmeSensorReading;

typedef struct _PhotoRequest {
    bool has_device_info;
    DeviceInfo device_info;
    bool has_timestamp;
    google_protobuf_Timestamp timestamp;
    int32_t count;
} PhotoRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _TouchValue_MIN TouchValue_NONE
#define _TouchValue_MAX TouchValue_HIGH
#define _TouchValue_ARRAYSIZE ((TouchValue)(TouchValue_HIGH+1))


#define TouchSensorReading_touch_value_ENUMTYPE TouchValue





/* Initializer values for message structs */
#define DeviceInfo_init_default                  {0, ""}
#define TouchSensorReading_init_default          {false, DeviceInfo_init_default, false, google_protobuf_Timestamp_init_default, _TouchValue_MIN}
#define GasSensorReading_init_default            {false, DeviceInfo_init_default, false, google_protobuf_Timestamp_init_default, 0}
#define BmeSensorReading_init_default            {false, DeviceInfo_init_default, false, google_protobuf_Timestamp_init_default, 0, 0, 0}
#define PhotoRequest_init_default                {false, DeviceInfo_init_default, false, google_protobuf_Timestamp_init_default, 0}
#define DeviceInfo_init_zero                     {0, ""}
#define TouchSensorReading_init_zero             {false, DeviceInfo_init_zero, false, google_protobuf_Timestamp_init_zero, _TouchValue_MIN}
#define GasSensorReading_init_zero               {false, DeviceInfo_init_zero, false, google_protobuf_Timestamp_init_zero, 0}
#define BmeSensorReading_init_zero               {false, DeviceInfo_init_zero, false, google_protobuf_Timestamp_init_zero, 0, 0, 0}
#define PhotoRequest_init_zero                   {false, DeviceInfo_init_zero, false, google_protobuf_Timestamp_init_zero, 0}

/* Field tags (for use in manual encoding/decoding) */
#define DeviceInfo_id_tag                        1
#define DeviceInfo_name_tag                      2
#define TouchSensorReading_device_info_tag       1
#define TouchSensorReading_timestamp_tag         2
#define TouchSensorReading_touch_value_tag       3
#define GasSensorReading_device_info_tag         1
#define GasSensorReading_timestamp_tag           2
#define GasSensorReading_gas_value_tag           3
#define BmeSensorReading_device_info_tag         1
#define BmeSensorReading_timestamp_tag           2
#define BmeSensorReading_temperature_value_tag   3
#define BmeSensorReading_pressure_value_tag      4
#define BmeSensorReading_humidity_value_tag      5
#define PhotoRequest_device_info_tag             1
#define PhotoRequest_timestamp_tag               2
#define PhotoRequest_count_tag                   3

/* Struct field encoding specification for nanopb */
#define DeviceInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    id,                1) \
X(a, STATIC,   SINGULAR, STRING,   name,              2)
#define DeviceInfo_CALLBACK NULL
#define DeviceInfo_DEFAULT NULL

#define TouchSensorReading_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         2) \
X(a, STATIC,   SINGULAR, UENUM,    touch_value,       3)
#define TouchSensorReading_CALLBACK NULL
#define TouchSensorReading_DEFAULT NULL
#define TouchSensorReading_device_info_MSGTYPE DeviceInfo
#define TouchSensorReading_timestamp_MSGTYPE google_protobuf_Timestamp

#define GasSensorReading_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         2) \
X(a, STATIC,   SINGULAR, INT32,    gas_value,         3)
#define GasSensorReading_CALLBACK NULL
#define GasSensorReading_DEFAULT NULL
#define GasSensorReading_device_info_MSGTYPE DeviceInfo
#define GasSensorReading_timestamp_MSGTYPE google_protobuf_Timestamp

#define BmeSensorReading_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         2) \
X(a, STATIC,   SINGULAR, INT32,    temperature_value,   3) \
X(a, STATIC,   SINGULAR, UINT32,   pressure_value,    4) \
X(a, STATIC,   SINGULAR, INT32,    humidity_value,    5)
#define BmeSensorReading_CALLBACK NULL
#define BmeSensorReading_DEFAULT NULL
#define BmeSensorReading_device_info_MSGTYPE DeviceInfo
#define BmeSensorReading_timestamp_MSGTYPE google_protobuf_Timestamp

#define PhotoRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  device_info,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  timestamp,         2) \
X(a, STATIC,   SINGULAR, INT32,    count,             3)
#define PhotoRequest_CALLBACK NULL
#define PhotoRequest_DEFAULT NULL
#define PhotoRequest_device_info_MSGTYPE DeviceInfo
#define PhotoRequest_timestamp_MSGTYPE google_protobuf_Timestamp

extern const pb_msgdesc_t DeviceInfo_msg;
extern const pb_msgdesc_t TouchSensorReading_msg;
extern const pb_msgdesc_t GasSensorReading_msg;
extern const pb_msgdesc_t BmeSensorReading_msg;
extern const pb_msgdesc_t PhotoRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define DeviceInfo_fields &DeviceInfo_msg
#define TouchSensorReading_fields &TouchSensorReading_msg
#define GasSensorReading_fields &GasSensorReading_msg
#define BmeSensorReading_fields &BmeSensorReading_msg
#define PhotoRequest_fields &PhotoRequest_msg

/* Maximum encoded size of messages (where known) */
#define BmeSensorReading_size                    116
#define DeviceInfo_size                          62
#define GasSensorReading_size                    99
#define MESSAGES_PB_H_MAX_SIZE                   BmeSensorReading_size
#define PhotoRequest_size                        99
#define TouchSensorReading_size                  90

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
